=== srjaime99/FTILand_P08/datos/ej1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Definición del tipo de datos para el atributo clave -->
  <xs:simpleType name="t_clave">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]*[a-zA-Z0-9]{8}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo de datos para el elemento 'id' -->
  <xs:simpleType name="t_id">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}-\d{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo de datos para el atributo estado -->
  <xs:simpleType name="t_estado">
    <xs:restriction base="xs:string">
      <xs:enumeration value="OP"/>
      <xs:enumeration value="OB"/>
      <xs:enumeration value="CE"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo de datos para el atributo tipo -->
  <xs:simpleType name="t_tipo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Montaña rusa"/>
      <xs:enumeration value="Acuática"/>
      <xs:enumeration value="Giratoria"/>
      <xs:enumeration value="Atracción"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo de datos para el atributo nivel -->
  <xs:simpleType name="t_nivel">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Infantil"/>
      <xs:enumeration value="Suave"/>
      <xs:enumeration value="Moderada"/>
      <xs:enumeration value="Intensa"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo de datos para el atributo expres -->
  <xs:simpleType name="t_expres">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Sí"/>
      <xs:enumeration value="No"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo de datos para el atributo ult_revis -->
  <xs:simpleType name="t_ult_revis">
    <xs:restriction base="xs:string">
      <xs:pattern value="(([0-2][0-9]|3[0-1])(\/|-)(0[1-9]|1[0-2])(\/|-)2(\d{3}))?|\s*"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo de datos para las alturas -->
  <xs:simpleType name="t_altura">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d*(\.\d{1,2})?"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo complejo para el elemento 'atraccion' -->
  <xs:complexType name="t_atraccion">
    <xs:sequence>
      <!-- Definición de los elementos dentro de 'atraccion' -->
      <xs:element name="id" type="t_id"/>
      <xs:element name="nombre_com" type="xs:string"/>
      <xs:element name="estado" type="t_estado"/>
      <!-- Uso del tipo de altura definido -->
      <xs:element name="alt_min" type="t_altura"/>
      <xs:element name="alt_max" type="t_altura"/>
      <xs:element name="tipo" type="t_tipo"/>
      <xs:element name="nivel" type="t_nivel"/>
      <xs:element name="expres" type="t_expres"/>
      <xs:element name="ult_revis" type="t_ult_revis"/>
    </xs:sequence>
    <!-- Definición del atributo de 'atraccion' -->
    <xs:attribute name="clave" type="t_clave" use="required"/>
  </xs:complexType>

  <!-- Definición del tipo complejo para el elemento 'area' -->
  <xs:complexType name="t_area">
    <xs:sequence>
      <!-- Definición de los elementos dentro de 'area' -->
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="atracciones">
        <!-- Definición de los elementos dentro de 'atracciones' -->
        <xs:complexType>
          <xs:sequence>
            <xs:element name="atraccion" type="t_atraccion" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
        <!-- Restricción 'unique' para asegurar claves únicas -->
        <xs:unique name="unique_clave">
          <xs:selector xpath="atraccion"/>
          <xs:field xpath="@clave"/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- Definición del tipo de datos para el atributo rol -->
  <xs:simpleType name="t_rol">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Responsable"/>
      <xs:enumeration value="Tecnico"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definición del tipo de datos para el elemento id_empleado -->
  <xs:simpleType name="t_id_empelado">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0,1]\d{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definicion del tipo complejo para el elemento 'empelado'-->
  <xs:complexType name="t_empleado">
    <xs:sequence>
      <!-- Definición de los elementos dentro de 'area' -->
      <xs:element name="id_empleado" type="t_id_empelado"/>
      <xs:element name="puesto" type="xs:string"/><!--limitar a que sea uno q exista-->
      <xs:element name="rol" type="t_rol"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Definicion del tipo complejo para el elemento 'areas'-->
  <xs:complexType name="t_areas">
    <xs:sequence>
      <!-- Definición de los elementos dentro de 'areas' -->
      <xs:element name="area" type="t_area" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Definicion del tipo complejo para el elemento 'empleados'-->
  <xs:complexType name="t_empleados">
    <xs:sequence>
      <!-- Definición de los elementos dentro de 'empleados' -->
      <xs:element name="empleado" type="t_empleado" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Definición del tipo complejo para el elemento 'parque' -->
  <xs:complexType name="t_parque">
    <xs:sequence>
      <!-- Definición de los elementos dentro de 'parque' -->
      <xs:element name="areas" type="t_areas"/>
      <xs:element name="empleados" type="t_empleados"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Definición del elemento raíz 'parque' -->
  <xs:element name="parque" type="t_parque"/>

</xs:schema>

=== srjaime99/FTILand_P08/data/ej2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<parque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ej1.xsd">
    <areas>
        <area>
            <nombre>Plaza Mayor</nombre>
            <atracciones>
                <atraccion clave="1q2w3e4r">
                    <id>PLA-01</id>
                    <nombre_com>Carrusel</nombre_com>
                    <estado>OP</estado>
                    <alt_min>0.80</alt_min>
                    <alt_max></alt_max>
                    <tipo>Atracción</tipo>
                    <nivel>Suave</nivel>
                    <expres>No</expres>
                    <ult_revis>20/02/2023</ult_revis>
                </atraccion>
                <atraccion clave="1a2s3d4f">
                    <id>PLA-02</id>
                    <nombre_com>Motospeed</nombre_com>
                    <estado>OP</estado>
                    <alt_min>1.20</alt_min>
                    <alt_max>1.95</alt_max>
                    <tipo>Montaña rusa</tipo>
                    <nivel>Moderada</nivel>
                    <expres>Sí</expres>
                    <ult_revis>01/11/2023</ult_revis>
                </atraccion>
                <atraccion clave="1z2x3c4v">
                    <id>PLA-03</id>
                    <nombre_com>Caída libre</nombre_com>
                    <estado>OP</estado>
                    <alt_min>1.40</alt_min>
                    <alt_max>1.95</alt_max>
                    <tipo>Atracción</tipo>
                    <nivel>Intensa</nivel>
                    <expres>Sí</expres>
                    <ult_revis>02/01/2024</ult_revis>
                </atraccion>
            </atracciones>
        </area>
        <area>
            <nombre>The Far West</nombre>
            <atracciones>
                <atraccion clave="0o9i8u7y">
                    <id>TFW-01</id>
                    <nombre_com>Saloon</nombre_com>
                    <estado>OP</estado>
                    <alt_min>1.30</alt_min>
                    <alt_max></alt_max>
                    <tipo>Giratoria</tipo>
                    <nivel>Moderada</nivel>
                    <expres>Sí</expres>
                    <ult_revis>01/01/2021</ult_revis>
                </atraccion>
                <atraccion clave="0k9j8h7g">
                    <id>TFW-02</id>
                    <nombre_com>Iron Cowboy</nombre_com>
                    <estado>OB</estado>
                    <alt_min>1.20</alt_min>
                    <alt_max>1.90</alt_max>
                    <tipo>Montaña rusa</tipo>
                    <nivel>Intensa</nivel>
                    <expres>Sí</expres>
                    <ult_revis></ult_revis>
                </atraccion>
                <atraccion clave="0m9n8b7v">
                    <id>TFW-03</id>
                    <nombre_com>Rápidos de Río Grande</nombre_com>
                    <estado>OP</estado>
                    <alt_min>1.00</alt_min>
                    <alt_max></alt_max>
                    <tipo>Acuática</tipo>
                    <nivel>Moderada</nivel>
                    <expres>Sí</expres>
                    <ult_revis>02/01/2024</ult_revis>
                </atraccion>
            </atracciones>
        </area>
        <area>
            <nombre>Territorio Pirata</nombre>
            <atracciones>
                <atraccion clave="1q0o2w9i">
                    <id>PIR-01</id>
                    <nombre_com>Barco Pirata</nombre_com>
                    <estado>CE</estado>
                    <alt_min>1.20</alt_min>
                    <alt_max></alt_max>
                    <tipo>Atracción</tipo>
                    <nivel>Moderada</nivel>
                    <expres>No</expres>
                    <ult_revis></ult_revis>
                </atraccion>
                <atraccion clave="1a0k2s9j">
                    <id>PIR-02</id>
                    <nombre_com>Minibarco</nombre_com>
                    <estado>OP</estado>
                    <alt_min></alt_min>
                    <alt_max>1.20</alt_max>
                    <tipo>Atracción</tipo>
                    <nivel>Suave</nivel>
                    <expres>No</expres>
                    <ult_revis>03/02/2024</ult_revis>
                </atraccion>
                <atraccion clave="1z0m2x9n">
                    <id>PIR-03</id>
                    <nombre_com>El Kraken</nombre_com>
                    <estado>CE</estado>
                    <alt_min>1.40</alt_min>
                    <alt_max></alt_max>
                    <tipo>Giratoria</tipo>
                    <nivel>Intensa</nivel>
                    <expres>Sí</expres>
                    <ult_revis>04/08/2023</ult_revis>
                </atraccion>
                <atraccion clave="5tgb6tfc">
                    <id>PIR-04</id>
                    <nombre_com>Siete Mares</nombre_com>
                    <estado>OP</estado>
                    <alt_min>1.40</alt_min>
                    <alt_max></alt_max>
                    <tipo>Montaña rusa</tipo>
                    <nivel>Intensa</nivel>
                    <expres>Sí</expres>
                    <ult_revis>02/12/2023</ult_revis>
                </atraccion>
            </atracciones>
        </area>
        <area>
            <nombre>Cool Children Land</nombre>
            <atracciones>
                <atraccion clave="56ttfgcb">
                    <id>CCL-01</id>
                    <nombre_com>Pequecoaster</nombre_com>
                    <estado>OP</estado>
                    <alt_min>0.80</alt_min>
                    <alt_max></alt_max>
                    <tipo>Montaña rusa</tipo>
                    <nivel>Suave</nivel>
                    <expres>Sí</expres>
                    <ult_revis>02/12/2023</ult_revis>
                </atraccion>
            </atracciones>
        </area>
        <area>
            <nombre>Calle Futura</nombre>
            <atracciones>
                <atraccion clave="1qaz2wsx">
                    <id>FUT-01</id>
                    <nombre_com>Nave Alocada</nombre_com>
                    <estado>OP</estado>
                    <alt_min>1.00</alt_min>
                    <alt_max></alt_max>
                    <tipo>Giratoria</tipo>
                    <nivel>Moderada</nivel>
                    <expres>No</expres>
                    <ult_revis>04/08/2023</ult_revis>
                </atraccion>
                <atraccion clave="3edc4rfv">
                    <id>FUT-02</id>
                    <nombre_com>AquaUFO</nombre_com>
                    <estado>OP</estado>
                    <alt_min>1.00</alt_min>
                    <alt_max>1.90</alt_max>
                    <tipo>Acuática</tipo>
                    <nivel>Moderada</nivel>
                    <expres>Sí</expres>
                    <ult_revis>01/11/2019</ult_revis>
                </atraccion>
            </atracciones>
        </area>
    </areas>
    <empleados>
        <empleado>
            <id_empleado>1001</id_empleado>
            <puesto>PLA-01</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1002</id_empleado>
            <puesto>PLA-02</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1003</id_empleado>
            <puesto>PLA-03</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1004</id_empleado>
            <puesto>TFW-01</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1005</id_empleado>
            <puesto>TFW-02</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1006</id_empleado>
            <puesto>TFW-03</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1007</id_empleado>
            <puesto>PIR-01</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1008</id_empleado>
            <puesto>PIR-02</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1009</id_empleado>
            <puesto>PIR-03</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1010</id_empleado>
            <puesto>PIR-04</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1011</id_empleado>
            <puesto>CCL-01</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1012</id_empleado>
            <puesto>CCL-02</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>1013</id_empleado>
            <puesto>CCL-03</puesto>
            <rol>Tecnico</rol>
        </empleado>
        <empleado>
            <id_empleado>0001</id_empleado>
            <puesto>Plaza Mayor</puesto>
            <rol>Responsable</rol>
        </empleado>
        <empleado>
            <id_empleado>0002</id_empleado>
            <puesto>The Far West</puesto>
            <rol>Responsable</rol>
        </empleado>
        <empleado>
            <id_empleado>0003</id_empleado>
            <puesto>Territorio Pirata</puesto>
            <rol>Responsable</rol>
        </empleado>
        <empleado>
            <id_empleado>0004</id_empleado>
            <puesto>Cool Children Land3</puesto>
            <rol>Responsable</rol>
        </empleado>
        <empleado>
            <id_empleado>0005</id_empleado>
            <puesto>Calle Futura</puesto>
            <rol>Responsable</rol>
        </empleado>
    </empleados>
</parque>
